services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
      - ${FILEPATH}:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MEMCACHED_HOST=memcache
      - MEMCACHED_PORT=11211
    depends_on:
      - redis
      - memcache
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly no
    networks:
      - app-network

  memcache:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: